site_name: Shift

theme:
  name: "material"
  features:
    - search.suggest
    - sarch.highlight
    - content.tabs.link
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
plugins:
  - mkdocstrings
  - search
  - mkdocs-jupyter:
      theme: dark
      include: ["*.ipynb"] 

repo_url: https://github.com/nrel/shift
repo_name: nrel/shift



extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.33.1/plotly.min.js


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - codehilite
  - pymdownx.details


nav:
  - Welcome: index.md
  - Tutorials: 
    - synthetic_feeder_chennai: sample-1.ipynb
  - How to Guides: how-to-guides.md
  - References:
    - geometry: geometry.md
    - clustering: clustering.md
    - exceptions: exceptions.md
    - facade: facade.md
    - feeder_network: feeder_network.md
    - graph: graph.md
    - line_section: line_section.md
    - load_builder: load_builder.md
    - load: load.md
    - network_plots: network_plots.md
    - primary_network_builder: primary_network_builder.md
    - secondary_network_builder: secondary_network_builder.md
    - transformer_builder: transformer_builder.md
    - transformer: transformer.md
    - utils: utils.md
    - exporter.opendss: opendss.md
  - Theoritical Explanation: explanation.md
  - Guide to Developers: developers-guide.md
