site_name: Shift

theme:
  name: "material"
  features:
    - search.suggest
    - sarch.highlight
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
plugins:
  - mkdocstrings
  - search

repo_url: https://github.com/nrel/shift
repo_name: nrel/shift

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


nav:
  - Welcome: index.md
  - Tutorials: tutorials.md
  - How to Guides: how-to-guides.md
  - References:
    - geometry: geometry.md
  - Theoritical Explanation: explanation.md
  - Guide to Developers: developers-guide.md